In [4]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
import mnist
from collections import Counter

In [2]:
def load_dataset(cached_dir):
    '''
    Get MNIST data using mnist library
    :params cached_dir: folder path to cache mnist data
    :return: list of train sets and test sets
    '''
    mnist.temporary_dir = lambda: cached_dir
    train_images = mnist.train_images()
    train_labels = mnist.train_labels()
    test_images = mnist.test_images()
    test_labels = mnist.test_labels()
    
    return [train_images, train_labels, test_images, test_labels]

# load datasets
mnist_dir = '../z_datasets/MNIST/'
train_X, train_y, test_X, test_y = load_dataset(mnist_dir)

In [40]:
# craete a dataframe for training set
train_df = pd.DataFrame(train_X.reshape(train_X.shape[0], -1))
train_df['y'] = train_y
train_df = train_df.set_index('y')

In [41]:
train_df.head()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
y,,,,,,,,,,,,,,,,,,,,,
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [54]:
train_df.index.value_counts().sort_index()

0    5923
1    6742
2    5958
3    6131
4    5842
5    5421
6    5918
7    6265
8    5851
9    5949
Name: y, dtype: int64

In [81]:
def get_prob_distribution(train_df, n_features = 28*28, n_class = 10):
    '''
    Calculate the prior and conditional probability distributions
    :params train_df: dataframe for training set
    :params n_features: int, number of features, default is 28*28 because the MNIST data set is 28*28
    :params n_class: int, number of classes, default is 10 because we have labels 0~9
    :return: prior and conditional probability distributions
    '''
    # prior distribution Py
    # i.e. the probability of seeing y = label
    # an edge case is where label i does not exist in train but in test
    # in this case, the prior probability would be 0
    # and the posterior probability will always be 0 regardless of corresponding conditional probability
    # to avoid this scenario, we add 1 to the numerator and # of classes to the demoninator 
    Py = (train_df.index.value_counts() + 1)/(len(train_df) + n_class)
    
    # conditional probability Px_y, 
    # i.e. for y = label, the distribution of 0s and 1s for each feature x[i]
    grouped = train_df.astype(bool).groupby('y')
    Px_y_1 = (grouped.sum() + 1)/(grouped.count() + 2)
    Px_y_0 = 1 - Px_y_1

    return Py, (Px_y_0, Px_y_1)

In [82]:
Py, Px_y = get_prob_distribution(train_df)

In [72]:
Py.sort_index()

0    0.098717
1    0.112365
2    0.099300
3    0.102183
4    0.097367
5    0.090352
6    0.098634
7    0.104416
8    0.097517
9    0.099150
Name: y, dtype: float64

In [83]:
# probability of xi = 0
Px_y[0].sort_index()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
y,,,,,,,,,,,,,,,,,,,,,
0,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,...,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831
1,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852,...,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852,0.999852
2,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,...,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832
3,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837,...,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837,0.999837
4,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,...,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829
5,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816,...,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816,0.999816
6,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,...,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831,0.999831
7,0.999840,0.999840,0.999840,0.999840,0.999840,0.999840,0.999840,0.999840,0.999840,0.999840,...,0.985799,0.992820,0.996809,0.998564,0.999043,0.999521,0.999840,0.999840,0.999840,0.999840
8,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,...,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829,0.999829
9,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,0.999832,...,0.998488,0.998320,0.998656,0.998824,0.999496,0.999832,0.999832,0.999832,0.999832,0.999832

In [84]:
# probability of xi = 1
Px_y[1].sort_index()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
y,,,,,,,,,,,,,,,,,,,,,
0,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,...,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169
1,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148,...,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148,0.000148
2,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,...,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168
3,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163,...,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163,0.000163
4,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,...,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171
5,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184,...,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184,0.000184
6,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,...,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169,0.000169
7,0.000160,0.000160,0.000160,0.000160,0.000160,0.000160,0.000160,0.000160,0.000160,0.000160,...,0.014201,0.007180,0.003191,0.001436,0.000957,0.000479,0.000160,0.000160,0.000160,0.000160
8,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,...,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171,0.000171
9,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,0.000168,...,0.001512,0.001680,0.001344,0.001176,0.000504,0.000168,0.000168,0.000168,0.000168,0.000168

In [129]:
def naive_bayes(x, Py, Px_y, n_features = 28*28, n_class = 10):
    '''
    Probability estimation using naive bayes
    :params Py: prior probability distribution, P(Y=y)
    :params Px_y: conditional probability distributions, Px_y = P(X=x|Y=y)
    :params x: feature vector of the sample to be estimated
    :params n_features: int, number of features, default is 28*28 because the MNIST data set is 28*28
    :params n_class: int, number of classes, default is 10 because we have labels 0~9 
    :return: return the estimated probability of all labels
    '''
    # recap: P(Y=y|X=x) = P(X=x|Y=y)*P(Y=y)/P(X=x)
    # For a given test case, P(X=x) is the same for all possible y values
    # Px = P(Y=y|X=x) * P(X=x) = P(Y=y|X=x) * C
    # Px = Px_y * Py = Px0 * Px1 * ... * Px784 = Px0_y * Px1_y * Px2_y * ....*Px784_y * Py
    # as p in range(0, 1), we transform it into log to avoid vanishing probability
    # log_Px = log_Px0 + log_Px1 + ... = log_Px0_y + log_Px1_y + ... + log_Py
    Px_y_0, Px_y_1 = Px_y
    Px_y_0 = Px_y_0.apply(np.log)
    Px_y_1 = Px_y_1.apply(np.log)
    Py = Py.apply(np.log)
    
    x = np.where(x == 0, 0, 1)
    Px = Px_y_0 * (1-x) + Px_y_1 * x
    Px = pd.concat([Px, Py], axis=1)
    Px = Px.sum(axis = 1)
    
    return Px.idxmax()

n = 0
naive_bayes(test_X.reshape(test_X.shape[0], -1)[n], Py, Px_y)

7

In [134]:
def predict(test_X, Py, Px_y):
    '''
    Predict labels for cases in test_X
    :params train_X: train image dataset
    :params train_y: train label dataset
    :params test_X: test image dataset
    :params test_y: test label dataset
    :return: predicted label for all tests
    '''
    # calculate the prior and conditional probability distributions
    pred = []
    n_y = len(test_X)
    
    for i in range(n_y):
        if i % 1000 == 0:
            print('Predicting test {} to {}'.format(i, min(n_y, i+1000-1)))
        label = naive_bayes(test_X[i], Py, Px_y)
        pred.append(label)
            
    return pred

Py, Px_y = get_prob_distribution(train_df)
predictions = predict(test_X.reshape(test_X.shape[0], -1), Py, Px_y)

Predicting test 0 to 999
Predicting test 1000 to 1999
Predicting test 2000 to 2999
Predicting test 3000 to 3999
Predicting test 4000 to 4999
Predicting test 5000 to 5999
Predicting test 6000 to 6999
Predicting test 7000 to 7999
Predicting test 8000 to 8999
Predicting test 9000 to 9999

In [132]:
def evaluate(predictions, actual):
    '''
    :return: predicted labels for all tests
    :actual: true labels
    :return: accuracy
    '''
    accuracy = np.sum(predictions == actual)*1./len(actual)
    return accuracy

accuracy = evaluate(predictions, test_y)
print(accuracy)

0.8413

In [136]:
print(classification_report(test_y, predictions))

             precision    recall  f1-score   support

          0       0.91      0.91      0.91       980
          1       0.90      0.96      0.93      1135
          2       0.89      0.83      0.86      1032
          3       0.76      0.84      0.80      1010
          4       0.83      0.81      0.82       982
          5       0.82      0.70      0.76       892
          6       0.89      0.89      0.89       958
          7       0.93      0.85      0.89      1028
          8       0.75      0.78      0.77       974
          9       0.75      0.84      0.79      1009

avg / total       0.84      0.84      0.84     10000

In [137]:
# use GaussianNB from sklearn
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(train_X.reshape(train_X.shape[0], -1), train_y)
predictions = clf.predict(test_X.reshape(test_X.shape[0], -1))

In [138]:
accuracy = evaluate(predictions, test_y)
print(accuracy)

0.5558

In [139]:
print(classification_report(test_y, predictions))

             precision    recall  f1-score   support

          0       0.79      0.89      0.84       980
          1       0.85      0.95      0.90      1135
          2       0.90      0.26      0.40      1032
          3       0.71      0.35      0.47      1010
          4       0.88      0.17      0.29       982
          5       0.55      0.05      0.09       892
          6       0.65      0.93      0.77       958
          7       0.88      0.27      0.42      1028
          8       0.28      0.67      0.40       974
          9       0.37      0.95      0.53      1009

avg / total       0.69      0.56      0.52     10000